src/polls/urls.py
from django.urls import include, path

import polls.tasks.answer_poll.urls as answer_urls
import polls.tasks.create_poll.urls as create_urls
import polls.views as views

urlpatterns = [
    path("", views.PollFilterView.as_view(), name="poll-filter"),
    path("<int:pk>/edit", views.PollUpdateView.as_view(), name="poll-update"),
    path("<int:pk>/delete", views.PollDeleteView.as_view(), name="poll-delete"),
    path("", include(create_urls)),
    path("", include(answer_urls)),
    path("<int:pk>/", views.QuestionFilterView.as_view(), name="question-filter"),
    path(
        "question/<int:pk>/",
        views.QuestionDetailView.as_view(),
        name="question-detail",
    ),
    path(
        "question/edit/<int:pk>/",
        views.QuestionUpdateView.as_view(),
        name="question-update",
    ),
    path(
        "question/<int:pk>/delete/",
        views.QuestionDeleteView.as_view(),
        name="question-delete",
    ),
    path(
        "option/<int:pk>/delete/",
        views.OptionDeleteView.as_view(),
        name="option-delete",
    ),
    path(
        "answer/<int:pk>/",
        views.AnswerFilterView.as_view(),
        name="answer-detail",
    ),
    path(
        "response/<int:pk>/delete",
        views.ResponseDeleteView.as_view(),
        name="response-delete",
    ),
    path(
        "answer/user/",
        views.UserResponseView.as_view(),
        name="user-response-detail",
    ),
    path(
        "answer/<int:pk>/delete",
        views.AnswerDeleteView.as_view(),
        name="answer-delete",
    ),
    path(
        "answer/<int:pk>/edit",
        views.AnswerEditView.as_view(),
        name="answer-edit",
    ),
]

src/uploader/urls.py
from django.urls import include, path, re_path
from django.views.generic.base import TemplateView

from songuploader.utils import LoginRequiredTemplateView, slice_song

from .forms import SubmissionUploadForm
from .views.file_views import FileDownload
from .views.submission_views import SubmissionCreateView, SubmissionUpdateView
from .views.views import IndexView, LoginView, LogoutView, DownloadPlaylistView

song_urlpatterns = [
    path(
        "choose/",
        LoginRequiredTemplateView.as_view(
            template_name="uploader/choose_upload_type.html"
        ),
        name="choose-song",
    ),
    path("from-youtube/", SubmissionCreateView.as_view(), name="from-youtube"),
    path(
        "from-youtube/update/<int:pk>",
        SubmissionUpdateView.as_view(),
        name="update-from-youtube",
    ),
    path(
        "from-file/",
        SubmissionCreateView.as_view(
            form_class=SubmissionUploadForm,
            update_name="update-from-file",
            submit_action=slice_song,
        ),
        name="from-file",
    ),
    path(
        "from-file/update/<int:pk>",
        SubmissionUpdateView.as_view(
            form_class=SubmissionUploadForm, submit_action=slice_song
        ),
        name="update-from-file",
    ),
    path("upload/", SubmissionCreateView.as_view(), name="upload"),
    path("playlist/", DownloadPlaylistView.as_view(), name="download-playlist")
]


urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("song/", include(song_urlpatterns)),
    re_path(r"^media/(?P<path>.*)/$", FileDownload.as_view(), name="download-file"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
]

src/uploader/models.py
import os
import pathlib

from django.contrib.auth import get_user_model
from django.core import validators
from django.db import models
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _

from theme.utils import generate_filename


class Submission(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)

    song_url = models.URLField(_("Song URL"), max_length=512, null=True)
    start_time = models.IntegerField(
        _("Start Time (in sec.)"),
        validators=[validators.MinValueValidator(0)],
        default=0,
    )
    end_time = models.IntegerField(
        _("End Time"),
        validators=[validators.MinValueValidator(1)],
        default=30,
    )

    song = models.FileField(
        _("Song File"),
        upload_to=generate_filename,
        validators=[validators.FileExtensionValidator(["mp3", "wav", "ogg"])],
        null=True,
    )

    def __str__(self):
        return self.user.get_username()

src/uploader/views/file_views.py
from pathlib import Path

from django.conf import settings
from django.http import FileResponse, Http404
from django.views.generic import View

from songuploader.utils import ConfiguredLoginViewMixin


class FileDownload(ConfiguredLoginViewMixin, View):
    def get(self, request, *args, **kwargs):
        file = Path(settings.MEDIA_ROOT).joinpath(kwargs.get("path")).absolute()
        try:
            f = open(file, "rb")
            return FileResponse(f)
        except (FileNotFoundError, IsADirectoryError):
            raise Http404

src/uploader/views/submission_views.py
from typing import Any

from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic.edit import CreateView, UpdateView
from django_q.tasks import async_chain, async_task

from songuploader.utils import ConfiguredLoginViewMixin, download_song, slice_song

from ..forms import SubmissionForm
from ..models import Submission


def download_slice(view, submission: Submission):
    async_chain(
        [
            (download_song, [submission]),
            (slice_song, [submission]),
        ]
    )


def slice_anon(view, submission: Submission):
    slice_song(submission)


class SubmissionCreateView(ConfiguredLoginViewMixin, CreateView):
    model = Submission
    form_class = SubmissionForm
    template_name = "uploader/upload_form.html"
    success_url = reverse_lazy("index")
    update_name = "update-from-youtube"
    submit_action = download_slice

    def get(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        if obj := Submission.objects.filter(user=self.request.user):
            return redirect(reverse(self.update_name, kwargs={"pk": obj.first().pk}))
        return super().get(request, *args, **kwargs)

    def form_valid(self, form):
        if Submission.objects.filter(user=self.request.user).exists():
            return HttpResponse(status=412)
        submission = Submission.objects.create(
            **form.cleaned_data, user=self.request.user
        )
        # async_task(self.submit_action, submission)
        self.submit_action(submission)
        return HttpResponseRedirect(self.success_url)


class SubmissionUpdateView(ConfiguredLoginViewMixin, UpdateView):
    model = Submission
    form_class = SubmissionForm
    template_name = "uploader/upload_form.html"
    success_url = reverse_lazy("index")
    submit_action = download_slice

    def form_valid(self, form):
        submission = form.save()

        # async_task(self.submit_action, submission)
        self.submit_action(submission)
        return HttpResponseRedirect(self.success_url)

src/uploader/views/views.py
import json
import logging
import os
import shutil
import time
from typing import Any

from django.contrib import messages
from django.contrib.auth import authenticate, get_user_model, login, logout
from django.core.files import File
from django.core.files.storage import default_storage
from django.http import HttpResponse, StreamingHttpResponse
from django.shortcuts import redirect, render
from django.utils.translation import gettext_lazy as _
from django.views.generic import TemplateView, View
from django.views.generic.edit import FormView

from polls.utils import get_user_polls
from songuploader.settings import MEDIA_ROOT, MEDIA_URL
from songuploader.utils import (
    ConfiguredLoginViewMixin,
    download_song_url,
    get_client_ip,
    slice_song_path,
)

from ..forms import LoginForm, PlaylistDownloadForm
from ..models import Submission

log = logging.getLogger("django")

User = get_user_model()


class LoginView(FormView):
    form_class = LoginForm
    template_name = "uploader/login_view.html"

    def form_valid(self, form) -> HttpResponse:
        user = authenticate(
            self.request,
            username=form.cleaned_data["username"],
            password=form.cleaned_data["password"],
        )
        ip = get_client_ip(self.request)

        if user is not None:
            login(self.request, user)
            log.info(f'"{ip} - {user} Login"')

            redirect_to = form.cleaned_data.get("redirect_to")
            return redirect(redirect_to if redirect_to else "/")
        else:
            log.warning(f'"{ip} - {form.cleaned_data["username"]} Login failed"')
            messages.error(self.request, _("Wrong username or password"))
            return self.form_invalid(form)


class LogoutView(View):
    def get(self, request, *args, **kwargs):
        log.info(f'"{get_client_ip(self.request)} - {self.request.user} Logout"')
        logout(request)
        return redirect("login")


class IndexView(ConfiguredLoginViewMixin, TemplateView):
    template_name = "uploader/index.html"

    def get_context_data(self, **kwargs: Any):
        context = super().get_context_data(**kwargs)
        context["has_song"] = Submission.objects.filter(user=self.request.user).first()
        context["polls"] = get_user_polls(self.request.user)
        return context


class DownloadPlaylistView(FormView):
    template_name = "uploader/playlist.html"
    form_class = PlaylistDownloadForm

    def process_upload(self, form):
        yield f'{json.dumps({"state":1})}\n'
        if not os.path.exists(os.path.join(MEDIA_ROOT, "tmp", "playlist")):
            os.mkdir(os.path.join(MEDIA_ROOT, "tmp", "playlist"))
        filepath = download_song_url(form.cleaned_data["song_url"], "default")
        file = open(
            slice_song_path(
                filepath,
                form.cleaned_data["start_time"],
                form.cleaned_data["end_time"],
            ),
            "rb",
        )
        song = File(file)
        yield f'{json.dumps({"state": 2})}\n'
        users = (
            User.objects.order_by("last_name", "first_name")
            .exclude(id__in=form.cleaned_data["user_excluder"])
            .prefetch_related("submission_set")
        )
        usercount = users.count()
        yield f'{json.dumps({"substep": 0, "max": usercount})}\n'
        for i, user in enumerate(users):
            if not user.submission_set.first():
                default_storage.save(
                    os.path.join("tmp/playlist", f"{i}_{user}.mp3"), song
                )
            else:
                song_path = user.submission_set.first().song.path
                shutil.copy2(
                    song_path,
                    os.path.join(
                        os.path.join(MEDIA_ROOT, "tmp", "playlist"), f"{i}_{user}.mp3"
                    ),
                )
        yield f'{json.dumps({"state": 3, "substep": usercount})}\n'
        shutil.make_archive(
            os.path.join(MEDIA_ROOT, "playlist"),
            "zip",
            os.path.join(MEDIA_ROOT, "tmp", "playlist"),
        )
        shutil.rmtree(os.path.join(MEDIA_ROOT, "tmp", "playlist"))
        print("Done")
        yield f'{json.dumps({"state": 4, "filepath": MEDIA_URL + "playlist.zip"})}\n'
        return

    def form_valid(self, form):
        response = StreamingHttpResponse(
            self.process_upload(form),
            content_type="text/event-stream",
            headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no"},
        )
        response["Cache-Control"] = "no-cache"
        response["X-Accel-Buffering"] = "no"
        return response

src/uploader/templates/uploader/choose_song.html
{% extends 'base_with_box.html' %}
{% load i18n %}
{% block title %}
    {% translate "Choose upload method" %}
{% endblock title %}

{% block content %}
    <a href="{% url 'from-youtube' %}" class="button is-large has-tooltip-arrow" data-tooltip="{% translate 'load song from youtube (recommended)' %}">
        Using Youtube
    </a>
    <a href="{% url 'from-file' %}" class="button is-large has-tooltip-arrow" data-tooltip="{% translate 'upload your own song from disk' %}">
        Using File
    </a>
{% endblock content %}

src/uploader/templates/uploader/choose_upload_type.html
{% extends "base_with_box.html" %}
{% load i18n %}
{% block title %}{% translate "Choose Music" %}{% endblock title %}
{% block content %}
    <h1 class="title is-2 has-text-centered">{% trans "How do you want to choose your song?" %}</h1>
    <div class="columns">
        <div class="column">
            <a href="{% url 'from-youtube' %}" class="button is-large is-fullwidth id-fullheight is-primary has-tooltip-arrow" data-tooltip="{% translate 'load song from youtube (recommended)' %}">
                <span class="icon is-large"><i class="fa-brands fa-youtube"></i></span>
                <br>
                {% translate "Using Youtube" %} 
            </a>
        </div>
        <div class="column">
            <a href="{% url 'from-file' %}" class="button is-large is-fullwidth id-fullheight is-primary has-tooltip-arrow" data-tooltip="{% translate 'upload your own song from disk' %}">
                <span class="icon is-large"><i class="fa-solid fa-file"></i></span>
                <br>
                {% translate "Using File" %}
            </a>
        </div>
    </div>

{% endblock content %}

src/uploader/templates/uploader/index.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}Abitur 2023 Songuploader{% endblock title %}

{% block content %}
<div class="tile is-ancestor">
    <div class="tile is-parent is-4 is-vertical">
        <div class="tile is-child box has-text-centered">
            <div class="icon is-large">
                <i class="fas fa-2x fa-solid fa-music has-text-{{has_song|yesno:'primary,danger'}}"></i>
            </div>
            <div>
                {% if has_song.song %}
                    <a href="{{has_song.song.url}}">{% translate "Song submitted" %}</a>
                {% elif has_song %}
                    <p>{% trans "Song processing" %}</p>
                {% else %}
                    <a href="{% url 'choose-song' %}">{% translate "Song missing" %}</a>
                {% endif %}
            </div>
        </div>
        <div class="tile is-child box has-text-centered">
            <div class="icon is-large">
                <i class="fas fa-2x fa-solid fa-wrench has-text-secondary"></i>
            </div>
            <p>{% translate "New features coming soon! Stay tuned" %}</p>
        </div>
    </div>
    {% with polls.count as poll_number %}
    <div class="tile is-parent is-vertical">
        <div class="tile is-child box has-text-centered">
            <div class="icon is-large">
                <i class="fas fa-2x fa-solid fa-poll {% if poll_number > 0 %}has-text-danger{% else %}has-text-primary{% endif %}"></i>
            </div>
            <aside class="menu">
                <p class="menu-label">
                    {% blocktrans %}{{poll_number}} polls need your attention{% endblocktrans %}
                </p>
                <ul class="menu-list">
                {% for poll in polls|slice:":5" %}
                    <li>
                        <a href="{% url 'poll-start' poll.id %}">
                            {% blocktrans %}Answer {{poll}}{% endblocktrans %}
                        </a>
                    </li>
                {% empty %}
                    <p>{% trans "Please remind your friends to view their polls" %}</p>
                {% endfor %}
                </ul>
                {% if poll_number > 5 %}
                    <a id="modal-trigger" data-target="PollModal" class="menu-label">{% trans "All Polls" %}</a>
                {% endif %}
            </aside>
        </div>
    </div>
    {% endwith %}
</div>
<div id="PollModal" class="modal">
  <div class="modal-background"></div>
  <div class="modal-card">
    <header class="modal-card-head">
      <p class="modal-card-title">{% trans "List Polls" %}</p>
      <button class="delete" aria-label="close"></button>
    </header>
    <section class="modal-card-body">
        <aside class="menu">
            <p class="menu-label">
                {% blocktrans %}{{poll_number}} polls need your attention{% endblocktrans %}
            </p>
            <ul class="menu-list">
            {% for poll in polls %}
                <li>
                    <a href="{% url 'poll-start' poll.id %}">
                        {% blocktrans %}Answer {{poll}}{% endblocktrans %}
                    </a>
                </li>
            {% empty %}
                <p>{% trans "No Polls" %}</p>
            {% endfor %}
            </ul>
        </aside>
    </section>
    <footer class="modal-card-foot">
    <button class="button is-info">{% trans "Close" %}</button>
    </footer>
  </div>
</div>
{% endblock content %}

src/uploader/templates/uploader/login_view.html
{% extends 'base_with_box.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% load i18n %}

{% block title %}Login{% endblock title %}
{% block content %}
<div><img src="{% static 'png/cap.png' %}" alt="" class="image is-one-third"></div>
<form action="." method="post">
    {% crispy form %}
</form>
<a class="button is-link is-outlined is-fullwidth mt-3" href="{% url 'password-reset' %}">{% trans "Forgot password?" %}</a>
{% endblock content %}

{% block scripts %}
    <script>
        const urlParams = new URLSearchParams(window.location.search);
        const pageSize = urlParams.get('redirect_to');

        document.querySelector("#redirect_to").value = pageSize;
    </script>
{% endblock scripts %}

src/uploader/templates/uploader/playlist.html
{% extends 'base_with_box.html' %}
{% load crispy_forms_tags %}
{% load i18n %}
{% load static %}
{% load i18n %}

{% block title %}Upload Song{% endblock title %}
{% block content %}
<div class="is-hidden" id="bulmastepsWrapper">
  <ul class="steps has-content-centered">
      <li class="steps-segment is-active">
        <span class="steps-marker ">
            <span class="icon">
              <i class="fa-solid fa-play"></i>
              <i class="fa-solid fa-play is-hidden"></i>
            </span>
        </span>
        <div class="steps-content">
          <p class="is-size-4">{% trans "Starting" %}</p>
        </div>
      </li>
      <li class="steps-segment">
        <span class="steps-marker ">
            <span class="icon">
              <i class="fa-solid fa-cloud-arrow-down"></i>
              <i class="fa-solid fa-arrows-rotate is-hidden"></i>
            </span>
        </span>
        <div class="steps-content">
          <p class="is-size-4">{% trans "Song processing" %}</p>
        </div>
      </li>
      <li class="steps-segment">
        <span class="steps-marker ">
            <span class="icon">
              <i class="fa-solid fa-list"></i>
              <i class="fa-solid fa-arrows-rotate is-hidden"></i>
            </span>
        </span>
        <div class="steps-content">
          <p class="is-size-4">{% trans "Compiling Songs" %}</p>
        </div>
      </li>
      <li class="steps-segment">
        <span class="steps-marker ">
            <span class="icon">
              <i class="fa-solid fa-file-zipper"></i>
              <i class="fa-solid fa-arrows-rotate is-hidden"></i>
            </span>
        </span>
        <div class="steps-content">
          <p class="is-size-4">{% trans "Creating Archive" %}</p>
        </div>
      </li>
      <li class="steps-segment">
        <span class="steps-marker ">
          <span class="icon">
              <i class="fa fa-check"></i>
              <i class="fa fa-check is-hidden"></i>
          </span>
        </span>
        <div class="steps-content">
          <p class="is-size-4">{% trans "Done" %}</p>
        </div>
      </li>
  </ul>
</div>
<form method="post" class="spinnerIgnore" enctype="multipart/form-data" id="mainForm">
  <a href="." class="button is-danger is-fullwidth mb-3">{% trans "Reset Form" %}</a>
  {% crispy form %}
</form>
{% include 'helpers/submit_spinner.html' %}
{% endblock content %}
{% block scripts %}
<script>
    song_url = document.querySelector("#id_song_url");
    {% comment %} song = document.querySelector("#id_song") {% endcomment %}

    start_time = document.querySelector("#id_start_time");
    end_time = document.querySelector("#id_end_time");

    const box_content = document.getElementById("box-content")

    start_time.addEventListener("change", () => {
        data = start_time.value.match(/^(\d+):(\d+)$/g);
        a = 0;
        if (data){
            a = parseInt(data[0]) * 60;
            a = a+parseInt(data[1])
            start_time.value = a;
        }
        end_time.value=parseInt(start_time.value)+30;
    })

    const form = document.getElementById("mainForm")
    const bulmasteps = document.querySelectorAll(".steps-segment")
    const bulmastepsWrapper = document.querySelector("#bulmastepsWrapper")
    form.addEventListener("submit", async (submitEvent) => {
        submitEvent.preventDefault();
        var formData = new FormData(form)

        response = await fetch(".", {
            method: "POST",
            credentials: "same-origin",
            body: formData
        })
        if(response.headers.get("content-type") !== "text/event-stream"){
          var text = await response.text()
          document.getElementsByTagName("html")[0].innerHTML = text
          return
        } else {
          bulmastepsWrapper.classList.remove("is-hidden")
          form.remove()
        };
        // To recieve data as a string we use TextDecoderStream class in pipethrough
        const reader = response.body.pipeThrough(new TextDecoderStream()).getReader()


        while (true) {
            const {value, done} = await reader.read();
            if(done) break;
            console.log(value)
            data = JSON.parse(value)
            var state = parseInt(data.state)
            if(state) {
                bulmasteps[state].classList.toggle("is-active")
                var curr_icon = bulmasteps[state].childNodes[1].childNodes[1]
                if(state < 4){
                  curr_icon.classList.toggle("fa-pulse")
                }
                var curr_children = curr_icon.childNodes
                for (let i = 0; i < curr_children.length; i++){
                  try {curr_children[i].classList.toggle("is-hidden")
                } catch {}
              }
                bulmasteps[state-1].classList.toggle("is-active")
                var curr_icon = bulmasteps[state-1].childNodes[1].childNodes[1]
                if(state > 1){
                  curr_icon.classList.toggle("fa-pulse")
                }
                var curr_children = curr_icon.childNodes
                for (let i = 0; i < curr_children.length; i++){
                  try {curr_children[i].classList.toggle("is-hidden")
                } catch {}
              }
            }
            var substep = data.substep
            
            var filepath = data.filepath
            if(filepath){
              box_content.innerHTML += `<button onclick="window.open('${filepath}'); window.location.href = '{% url 'index' %}'" class="button is-primary is-fullwidth"><i class="fa-solid fa-file-zipper"></i>  {% trans "Download Archive" %}</button>`
            }
        }
    })

</script>
{% endblock scripts %}

src/uploader/templates/uploader/upload_form.html
{% extends 'base_with_box.html' %}
{% load crispy_forms_tags %}

{% block title %}Upload Song{% endblock title %}
{% block content %}
<form method="post" enctype="multipart/form-data" id="mainForm">
    {% crispy form %}
</form>
{% include 'helpers/submit_spinner.html' %}
{% endblock content %}
{% block scripts %}
<script>
    start_time = document.querySelector("#id_start_time");
    end_time = document.querySelector("#id_end_time");

    start_time.addEventListener("change", () => {
        data = start_time.value.match(/^(\d+):(\d+)$/g);
        a = 0;
        if (data){
            a = parseInt(data[0]) * 60;
            a = a+parseInt(data[1])
            start_time.value = a;
        }
        end_time.value=parseInt(start_time.value)+30;
    })

</script>
{% endblock scripts %}