src/polls/tasks/answer_poll/urls.py
from django.urls import include, path

from songuploader.utils import LoginRequiredTemplateView

from .views import QuestionAnswerView, StartPollView

urlpatterns = [
    path("start/<int:pk>/", StartPollView.as_view(), name="poll-start"),
    path(
        "question/answer/<int:pk>/",
        QuestionAnswerView.as_view(),
        name="question-answer",
    ),
    path(
        "done/",
        LoginRequiredTemplateView.as_view(
            template_name="polls/answer_poll/poll_done.html"
        ),
        name="poll-done",
    ),
]

src/polls/tasks/create_poll/urls.py
from django.urls import include, path

from .views import (
    CSVOptionCreateView,
    OptionCreateView,
    PollCreateView,
    QuestionCreateView,
)

urlpatterns = [
    path("create/", PollCreateView.as_view(), name="poll-create"),
    path(
        "option/create/<int:question_id>",
        OptionCreateView.as_view(),
        name="question-option-create",
    ),
    path(
        "option/create/csv/<int:pk>",
        CSVOptionCreateView.as_view(),
        name="question-option-csv-create",
    ),
    path(
        "question/create/<int:poll_id>",
        QuestionCreateView.as_view(),
        name="question-create",
    ),
]

src/polls/urls.py
from django.urls import include, path

import polls.tasks.answer_poll.urls as answer_urls
import polls.tasks.create_poll.urls as create_urls
import polls.views as views

urlpatterns = [
    path("", views.PollFilterView.as_view(), name="poll-filter"),
    path("<int:pk>/edit", views.PollUpdateView.as_view(), name="poll-update"),
    path("<int:pk>/delete", views.PollDeleteView.as_view(), name="poll-delete"),
    path("", include(create_urls)),
    path("", include(answer_urls)),
    path("<int:pk>/", views.QuestionFilterView.as_view(), name="question-filter"),
    path(
        "question/<int:pk>/",
        views.QuestionDetailView.as_view(),
        name="question-detail",
    ),
    path(
        "question/edit/<int:pk>/",
        views.QuestionUpdateView.as_view(),
        name="question-update",
    ),
    path(
        "question/<int:pk>/delete/",
        views.QuestionDeleteView.as_view(),
        name="question-delete",
    ),
    path(
        "option/<int:pk>/delete/",
        views.OptionDeleteView.as_view(),
        name="option-delete",
    ),
    path(
        "answer/<int:pk>/",
        views.AnswerFilterView.as_view(),
        name="answer-detail",
    ),
    path(
        "response/<int:pk>/delete",
        views.ResponseDeleteView.as_view(),
        name="response-delete",
    ),
    path(
        "answer/user/",
        views.UserResponseView.as_view(),
        name="user-response-detail",
    ),
    path(
        "answer/<int:pk>/delete",
        views.AnswerDeleteView.as_view(),
        name="answer-delete",
    ),
    path(
        "answer/<int:pk>/edit",
        views.AnswerEditView.as_view(),
        name="answer-edit",
    ),
]

src/polls/models.py
from crispy_bulma.widgets import FileUploadInput
from django import forms
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.db.models.signals import post_delete
from django.dispatch import receiver
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from pictures.models import PictureField
from tinymce import models as tinymce_models

from theme.widgets import slim_select


class Option(models.Model):
    name = models.CharField(_("Name"), max_length=64)
    question = models.ForeignKey(
        "polls.Question", verbose_name=_("Question"), on_delete=models.CASCADE
    )

    def __str__(self) -> str:
        return self.name

    class Meta:
        verbose_name = _("Option")
        verbose_name_plural = _("Options")


class AnswerValue(models.Model):
    answers = GenericRelation("polls.answer")

    def get_template(self):
        raise NotImplementedError("Method 'get_template' needs to be subclassed")

    class Meta:
        abstract = True


class CharAnswerValue(AnswerValue):
    value = models.CharField(_("Value"), max_length=512)

    def get_template(self):
        return "polls/answervalue/char.html"


def generate_poll_filename(self, filename):
    return "images/%s" % (filename)


class ImageAnswerValue(AnswerValue):
    width = models.IntegerField()
    height = models.IntegerField()
    value = PictureField(
        _("Image"),
        upload_to=generate_poll_filename,
        aspect_ratios=[None, "1/1"],
        width_field="width",
        height_field="height",
    )

    def get_template(self):
        return "polls/answervalue/image.html"


class MultipleChoiceAnswerValue(AnswerValue):
    value = models.ManyToManyField("polls.Option", verbose_name=_("Values"))

    def get_template(self):
        return "polls/answervalue/multiple.html"


class CHAR_ANSWER_FORM(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        kwargs.pop("question")
        super().__init__(*args, **kwargs)

    class Meta:
        model = CharAnswerValue
        fields = ["value"]


class IMAGE_ANSWER_FORM(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        kwargs.pop("question")
        super().__init__(*args, **kwargs)

    class Meta:
        model = ImageAnswerValue
        fields = ["value"]
        widgets = {"value": FileUploadInput}


class MULTIPLE_CHOICE_ANSWER_FORM(forms.ModelForm):
    def __init__(self, *args, **kwargs) -> None:
        self.question = kwargs.pop("question")
        self.max_answers = self.question.max_answers
        self.choices = self.question.option_set.all()

        super().__init__(*args, **kwargs)

        widget = None
        if self.choices.count() > 15:
            widget = slim_select.MultipleSlimSelect(max_answers=self.max_answers)
        else:
            widget = forms.widgets.CheckboxSelectMultiple

        self.fields["value"] = forms.ModelMultipleChoiceField(
            widget=widget,
            queryset=self.choices,
        )

    def clean_value(self):
        data = self.cleaned_data["value"]
        if data.count() > self.max_answers:
            raise forms.ValidationError(
                _("Only %(max_answers)s options possible"),
                code="invalid",
                params={"max_answers": self.max_answers},
            )
        return data

    class Meta:
        model = MultipleChoiceAnswerValue
        fields = ["value"]


class Poll(models.Model):
    name = models.CharField(_("Name"), max_length=64)
    description = tinymce_models.HTMLField(_("Description"))
    start_date = models.DateTimeField(_("Start Date"), auto_now_add=True)
    end_date = models.DateField(_("End Date"))
    can_answered_multiple = models.BooleanField(_("Can be answered multiple times"))

    def __str__(self) -> str:
        return self.name

    def get_absolute_url(self):
        return reverse("question-filter", kwargs={"pk": self.pk})

    class Meta:
        verbose_name = _("Poll")
        verbose_name_plural = _("Polls")
        permissions = [
            ("can_open_polls", _("Can open Polls")),
            ("can_close_polls", _("Can close Polls")),
        ]
        ordering = ["-end_date"]


class Question(models.Model):
    TYPE_CHOICES = (
        (0, _("Text Type")),
        (1, _("Image Type")),
        (2, _("Multiple Choice Type")),
    )
    FORM_OPTIONS = [CHAR_ANSWER_FORM, IMAGE_ANSWER_FORM, MULTIPLE_CHOICE_ANSWER_FORM]

    question_type = models.IntegerField(_("Question Type"), choices=TYPE_CHOICES)
    position = models.PositiveIntegerField(
        _("Position"), help_text=_("Order in which questions are displayed"), default=0
    )

    name = models.CharField(_("Name"), max_length=64)
    description = tinymce_models.HTMLField(_("Description"))
    max_answers = models.PositiveSmallIntegerField(
        _("Max Answers"),
        help_text=_("Max amounts of Answers that can be given"),
        default=1,
        blank=True,
    )
    created_at = models.DateTimeField(_("created at"), auto_now_add=True)

    poll = models.ForeignKey(
        "polls.Poll", verbose_name=_("Poll"), on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name

    def get_form(self):
        return self.FORM_OPTIONS[self.question_type]

    def get_absolute_url(self):
        return reverse("question-detail", kwargs={"pk": self.pk})

    class Meta:
        verbose_name = _("Question")
        verbose_name_plural = _("Questions")
        ordering = ["position", "created_at", "name"]


class Response(models.Model):
    poll = models.ForeignKey(
        "polls.Poll", verbose_name=_("Poll"), on_delete=models.CASCADE
    )
    user = models.ForeignKey(
        "auth.User", verbose_name=_("User"), on_delete=models.CASCADE
    )
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.poll} - {self.user}"

    class Meta:
        ordering = ["created_at"]


class Answer(models.Model):
    question = models.ForeignKey(
        "polls.Question", verbose_name=_("Question"), on_delete=models.CASCADE
    )
    response = models.ForeignKey(
        "polls.Response", verbose_name=_("Response"), on_delete=models.CASCADE
    )

    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    answer_value = GenericForeignKey("content_type", "object_id")

    class Meta:
        indexes = [
            models.Index(fields=["content_type", "object_id"]),
        ]

@receiver(post_delete, sender=Answer)
def delete_answer_value(sender, instance, **kwargs):
    print(instance, "deleted")
    if instance.answer_value:
        instance.answer_value.delete()

src/polls/forms.py
from crispy_bulma.layout import Column, Row, Submit
from crispy_forms.helper import FormHelper
from crispy_forms.layout import HTML, Button, Field, Layout
from django import forms
from django.utils.translation import gettext_lazy as _
from tinymce.widgets import TinyMCE

from polls.models import Option, Poll, Question


class QuestionForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Row(Column(Field("name")), Column(Field("position"))),
            Row(
                Column(Field("question_type")),
                Column("max_answers"),
            ),
            "description",
            Submit(
                "submit",
                _("Update Question") if self.initial else _("Create Question"),
                css_class="is-primary is-fullwidth is-rounded",
            ),
        )
        instance = getattr(self, "instance", None)
        if instance and instance.pk:
            self.fields["question_type"].disabled = True

    class Meta:
        model = Question
        fields = [
            "name",
            "position",
            "question_type",
            "description",
            "max_answers",
        ]

    def clean_max_answers(self):
        data = self.cleaned_data.get("max_answers", 1)
        data = 1 if data == None else data
        choice = self.cleaned_data["question_type"]
        if choice != 2 and data > 1:
            raise forms.ValidationError(
                _("Max Answers has to be one on this question type")
            )

        return data

    def clean_question_type(self):
        instance = getattr(self, "instance", None)
        if instance and instance.pk:
            return instance.question_type
        else:
            return self.cleaned_data.get("question_type", None)


class BaseOptionFormset(forms.BaseModelFormSet):
    def __init__(self, *args, **kwargs):
        super(BaseOptionFormset, self).__init__(*args, **kwargs)
        self.queryset = Option.objects.none()

src/polls/tasks/answer_poll/views.py
from typing import Any, Dict, Type

from django import forms, http
from django.contrib import messages
from django.core.exceptions import PermissionDenied
from django.forms import formset_factory
from django.http import HttpRequest, HttpResponse
from django.http.response import HttpResponse
from django.shortcuts import redirect
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.views import View
from django.views.generic import TemplateView
from django.views.generic.detail import SingleObjectMixin
from django.views.generic.edit import FormView

from polls.models import CHAR_ANSWER_FORM, Answer, Poll, Question, Response
from polls.utils import get_question
from songuploader.utils import ConfiguredLoginViewMixin


class StartPollView(ConfiguredLoginViewMixin, SingleObjectMixin, TemplateView):
    model = Poll
    template_name = "polls/answer_poll/start_poll.html"
    object = None

    def post(self, request, *args, **kwargs):
        response, idx = self.get_response()
        if not response:
            return redirect("index")

        return redirect("question-answer", pk=response.id)

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["object"] = self.get_object()
        return context

    def get_response(self):
        response = Response.objects.filter(user=self.request.user, poll=self.object)
        if response.exists():
            response = response.last()
            poll = response.poll
            # Check if Poll is already answered
            if response.answer_set.count() == poll.question_set.count():
                if not poll.can_answered_multiple:
                    messages.error(
                        self.request, _("You have already answered this poll")
                    )
                    return (None, None)
                return (self.create_poll(), 0)
            return (response, response.answer_set.count())
        return (self.create_poll(), 0)

    def dispatch(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        self.object = self.get_object()
        if self.object.end_date < timezone.now().date():
            messages.warning(request, _("Poll is closed"))
            return redirect("index")
        return super().dispatch(request, *args, **kwargs)

    def create_poll(self):
        response = Response(user=self.request.user, poll=self.object)
        response.save()
        return response


class QuestionAnswerView(ConfiguredLoginViewMixin, SingleObjectMixin, FormView):
    model = Response
    template_name = "polls/answer_poll/question_answer_form.html"

    def get(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        if not self.question:
            return redirect("poll-done")
        return super().get(request, *args, **kwargs)

    def form_valid(self, form: Any) -> HttpResponse:
        answer_value = form.save()
        Answer.objects.create(
            question=self.question, response=self.object, answer_value=answer_value
        )
        return redirect("question-answer", pk=self.object.id)

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super(FormView, self).get_context_data(**kwargs)
        context["poll"] = self.poll
        context["question"] = self.question
        context["question_idx"] = self.question_idx
        return context

    def get_form_class(self) -> type:
        if self.question:
            return self.question.get_form()
        return CHAR_ANSWER_FORM

    def get_form(self, form_class=None):
        """Return an instance of the form to be used in this view."""
        if form_class is None:
            form_class = self.get_form_class()
        return form_class(**self.get_form_kwargs(), question=self.question)

    def dispatch(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        self.object = self.get_object()
        self.poll = self.object.poll
        self.question_idx, self.question = get_question(request, self.poll)
        if not self.object.user == request.user:
            raise PermissionDenied()
        if self.object.answer_set.filter(question=self.question).exists():
            raise PermissionDenied()
        if self.poll.end_date < timezone.now().date():
            messages.warning(request, _("Poll is closed"))
            return redirect("index")
        return super().dispatch(request, *args, **kwargs)

src/polls/templates/polls/answer_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load i18n %}
{% load pictures %}
{% block title %}{% trans "List Answers for" %} {{ poll }}{% endblock title %}
{% block content %}
    <h1 class="title">{% trans "Inspect Answers" %}</h1>
    <button class="button is-link is-fullwidth mb-2" id="formToggleButton">
        <span class="icon-text">
            <span class="icon"><i class="fa-solid fa-filter"></i></span>
            <span>{% trans "Collapse / Expand Filter" %}</span>
        </span>
    </button>
    <form method="get" class="mb-2" id="filterForm">
        {{ filter.form | crispy }}
        <div class="field">
            <label for="id_page_size">{% trans "Page Size" %}</label>
            <div class="control">
                <div class="select is-fullwidth">
                    <select name="page_size" id="id_page_size">
                        <option value="25" {% if request.GET.page_size == "25" %}selected{% endif %}>25</option>
                        <option value="50" {% if request.GET.page_size == "50" %}selected{% endif %}>50</option>
                        <option value="100" {% if request.GET.page_size == "100" %}selected{% endif %}>100</option>
                    </select>
                </div>
            </div>
        </div>
        <button class="button is-primary is-fullwidth mb-2">{% trans "Select" %}</button>
        <a href="." class="button is-danger is-fullwidth mb-2">{% trans "Reset" %}</a>
        {% comment %} </div> {% endcomment %}
    </form>
    {% for response in page_obj %}
        <div class="card">
            <header class="card-header">
                <p class="card-header-title">
                    {% blocktranslate with counter=forloop.counter user=response.user %}Response #{{ counter }} by
                        {{ user }}{% endblocktranslate %}
                </p>
                <button class="card-header-icon card-toggle" aria-label="expand / collapse">
                <span class="icon">
                    <i class="fas fa-angle-down" aria-hidden="true"></i>
                </span>
                </button>
                <button class=" card-header-iconbutton is-small is-danger is-inverted " id="modal-trigger"
                        onclick="fill_data(this)" data-target="ResponseDeleteModal"
                        data-value="{% url 'response-delete' response.id %}"
                        data-form-extra-data-next="{% url 'answer-detail' response.poll.id %}">
                    <i class="fa-solid fa-trash"></i>
                </button>
            </header>
            <div class="card-content">
                {% for answer in response.answer_set.all %}
                    <div class="card">
                        <header class="card-header">
                            <p class="card-header-title">
                                {{ answer.question }}
                            </p>
                            <button class="card-header-icon card-toggle" aria-label="expand / collapse">
                            <span class="icon">
                                <i class="fas fa-angle-down" aria-hidden="true"></i>
                            </span>
                            </button>
                        </header>
                        <div class="card-content is-hidden">
                            {% include answer.answer_value.get_template with answer_value=answer.answer_value only %}
                        </div>
                        <footer class="card-footer is-hidden">
                            <a href="{% url 'answer-edit' answer.id %}" class="card-footer-item">{% trans "Edit" %}</a>
                            <button class="card-footer-item button is-ghost" id="modal-trigger"
                                    onclick="fill_data(this)" data-target="AnswerDeleteModal"
                                    data-value="{% url 'answer-delete' answer.id %}"
                                    data-form-extra-data-next="{% url 'answer-detail' response.poll.id %}">{% trans "Delete" %}</button>
                        </footer>
                    </div>
                {% endfor %}
            </div>
        </div>
        {% empty %}
        <p>{% trans "No User or User with answer selected" %}</p>
    {% endfor %}
    <div id="paginator" class="mt-5">
        {% include 'partials/paginator.html' with page_obj=page_obj %}
    </div>

    {% include 'partials/delete_modal.html' with modal_name="ResponseDeleteModal" object_type=_("Response") %}
    {% include 'partials/delete_modal.html' with modal_name="AnswerDeleteModal" object_type=_("Answer") %}
{% endblock content %}
{% block scripts %}
    <script>
        const filterForm = document.getElementById("filterForm")
        document.getElementById("formToggleButton").addEventListener("click", () => filterForm.classList.toggle("is-hidden"))

    </script>
{% endblock scripts %}

src/polls/templates/polls/answer_form.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% load extensions %}
{% block title %}{% trans "Edit Answer" %}{% endblock title %}
{% block content %}
    <h1 class="title">{% blocktrans %}Update Answer for {{question}}{% endblocktrans %}</h1>
    <div class="content">{{question.description | bleach}}</div>
    {% if question.question_type == 2 %}
        <p>{% blocktrans with max=question.max_answers %}<strong>{{max}}</strong> options can be selected{% endblocktrans %}</p>
    {% endif %}
    <form method="post" id="mainForm" enctype="multipart/form-data">
        {% csrf_token %}
        {{form | crispy}}
        <button class="button is-primary is-fullwidth is-rounded">{% trans "Submit" %}</button>
    </form>
    {% include 'helpers/submit_spinner.html' %}
{% endblock content %}
{% block scripts %}
<script>
    const form = document.querySelector("#mainForm");

    const update_checkboxes = () => {
        const checked = document.querySelectorAll(".checkbox>input:checked").length;
        const unchecked = document.querySelectorAll(".checkbox>input:not(:checked)");
        if(checked >= {{question.max_answers}}){
            unchecked.forEach((i) => i.setAttribute("disabled", "disabled"));
        }
        else{
            unchecked.forEach((i) => i.removeAttribute("disabled"));
        }
    }
    update_checkboxes();
    form.addEventListener("change", update_checkboxes);
</script>
{% endblock scripts %}

src/polls/templates/polls/csv_option_form.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block title %}{% trans "Load Options from csv" %}{% endblock title %}
{% block content %}
    <h1 class="title">{% trans "Load Options from csv" %}</h1>
    <h2>{% trans "Format of the csv file" %}</h2>
<div class="highlight"><pre><code>
name
{% blocktrans %}value1 (any arbitrary value)
value2
value3
...{% endblocktrans %}
</code></pre></div>
<br>
{% crispy form %}
{% include 'helpers/submit_spinner.html' %}
{% endblock content %}

src/polls/templates/polls/poll_filter.html
{% extends 'filter_generic.html' %}
{% load i18n %}
{% load extensions %}
{% block title %}{% trans "Polls" %}{% endblock title %}
{% block actions %}
    <div class="card-header-icon">
        <a href="{% url 'poll-create' %}" class="button is-link has-tooltip-arrow" data-tooltip="{% translate 'Add Poll' %}">
            <i class="fa-solid fa-square-poll-vertical"></i>
            <i class="fa-solid fa-plus pl-1"></i>
        </a>
    </div>
{% endblock actions %}
{% block table_content %}
    <tr>
        <td>
            <a href="{% url 'question-filter' obj.id %}">
                <strong>{{obj}}</strong><br>
                <p class="has-text-grey">{{obj.description|bleach |truncatewords:5}}</p>
            </a>
        </td>
        <td>
            <span>{{obj.start_date}}</span><br>
            <soan>{{obj.end_date}}</soan>
        </td>
        <td>
            <button class="button is-small is-danger is-inverted " id="modal-trigger" onclick="fill_data(this)" data-target="PollDeleteModal" data-value="{% url 'poll-delete' obj.id %}">
                <i class="fa-solid fa-trash"></i>
            </button>
        </td>
    </tr>
{% endblock table_content %}
{% block modals %}
    {% include 'partials/delete_modal.html' with modal_name="PollDeleteModal" object_type="Umfrage" %}
{% endblock modals %}

src/polls/templates/polls/question_detail.html
{% extends "base.html" %}
{% load i18n %}
{% load extensions %}
{% block title %}{% trans "Question" %} {{object}} {% endblock title %}
{% block content %}
    <nav class="breadcrumb" aria-label="breadcrumbs">
    <ul>
        <li><a href="{% url 'poll-filter' %}">{% trans "Polls" %}</a></li>
        <li><a href="{{object.poll.get_absolute_url}}">{{object.poll}}</a></li>
        <li class="is-active"><a href="#" aria-current="page">{{object}}</a></li>
    </ul>
    </nav>
    <div class="card mb-5">
        <div class="card-header">
            <h1 class="card-header-title title mb-0">{{object}}</h1>
            <span class="card-header-icon">
                <a href="{% url 'question-update' object.id %}"><i class="fa-solid fa-pen"></i></a>
            </span>
        </div>
        <div class="card-content">
            <div class="content mb-2">
                {{object.description | bleach}}
            </div>
            <div class="mb-2">
                <p class="has-text-gray">{% trans "Question Type" %}</p>
                <p class="is-size-5">{{object.get_question_type_display}}</p>
            </div>
            <div class="mb-2">
                <p class="has-text-gray">{% trans "Max Answers" %}</p>
                <p class="is-size-5">{{object.max_answers}}</p>
            </div>
        </div>
    </div>
    {% if object.question_type == 2 %}
        <div class="card mb-5">
            <div class="card-header">
                <h1 class="card-header-title title mb-0">{% trans "Responses" %}</h1>
            </div>
            <div class="card-content">
                <canvas id="myChart"></canvas>

                <div class="box mt-5">
                    <div class="has-text-centered m-2">
                        <h3 class="title is-4 m-0">{% trans "Current Winners" %}</h3>
                        <p class="heading">{% trans "Amount of votes" %}</p>
                    </div>
                    <div class="level">
                        {% for value in data|slice:question.max_answers %}
                        <div class="level-item has-text-centered">
                            <div>
                                <p class="heading">{{value.name|truncatechars:"14"}}</p>
                                <p class="title">{{value.count}}</p>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        <div class="card mb-5">
            <div class="card-header">
                <h1 class="card-header-title title mb-0">{% trans "Options" %}</h1>
                <span class="card-header-icon">
                    <a href="{% url 'question-option-create' object.id %}"><i class="fa-solid fa-add"></i></a>
                </span>
            </div>
            <div class="card-content">
                {% for option in object.option_set.all %}
                    <div class="columns">
                        <div class="column has-text-weight-bold">{{option}}</div>
                        <span class="card-header-icon">
                            <button class="button is-small is-danger is-inverted " id="modal-trigger" onclick="fill_data(this)" data-target="OptionDeleteModal" data-value="{% url 'option-delete' option.id %}">
                                <i class="fa-solid fa-trash"></i>
                            </button>
                        </span>
                    </div>
                {% empty %}
                <div class="is-fullwidth has-text-centered">{% trans "No options yet..." %}</div>
                {% endfor %}
            </div>
        </div>
    {% endif %}
{% include 'partials/delete_modal.html' with modal_name="OptionDeleteModal" object_type="Option" %}
{% endblock content %}

{% block scripts %}
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script charset="utf-8">
  const ctx = document.getElementById('myChart');
  const data = JSON.parse("{{data|slice:"15"|safe}}".replaceAll("'", "\""));
  const names = data.map(item => item.name);
  const counts = data.map(item => item.count);

  new Chart(ctx, {
    type: 'pie',
    data: {
      labels: names,
      datasets: [{
        label: '{% trans " # of Votes" %}',
        data: counts,
        borderWidth: 1,
      }]
    },
    options: {
      plugins: {
        legend: {
          lables: {
            font: {
              family: "BlinkMacSystemFont,-apple-system,'Segoe UI',Roboto,Oxygen,Ubuntu,Cantarell,'Fira Sans','Droid Sans','Helvetica Neue',Helvetica,Arial,sans-serif"
            }
          }
        }
      }
    },
  });
</script>
{% endblock scripts %}

src/polls/templates/polls/question_filter.html
{% extends 'filter_generic.html' %}
{% load i18n %}
{% block title %}{% trans "Questions for" %} {{poll}}{% endblock title %}
{% block actions %}
    <div class="card-header-icon">
        <a href="{% url 'answer-detail' poll.id %}" class="button is-link has-tooltip-arrow" data-tooltip="{% translate 'Show Answers' %}">
            <i class="fa-solid fa-flag-checkered"></i>
        </a>
        <a href="{% url 'poll-update' poll.id %}" class="button is-link has-tooltip-arrow" data-tooltip="{% translate 'Edit Poll' %}">
            <i class="fa-solid fa-pen"></i>
        </a>
        <a href="{% url 'question-create' poll.id %}" class="button is-link has-tooltip-arrow" data-tooltip="{% translate 'Add Question' %}">
            <i class="fa-solid fa-circle-question"></i>
            <i class="fa-solid fa-plus pl-1"></i>
        </a>
    </div>
{% endblock actions %}
{% block table_header %}
<thead>
    <tr>
        <td>
            {% trans "Position" %}
        </td>
        <td>
            {% trans "Name" %}
        </td>
        <td>
            {% trans "Question Type" %}
        </td>
        <td>
            {% trans "Max Answers" %}
        </td>
        <td>&nbsp;</td>
    </tr>
</thead>
{% endblock table_header %}
{% block table_content %}
    <tr>
        <td>
            <a href="{% url 'question-detail' obj.id %}">{{obj.position}}</a>
        </td>
        <td>
            <a href="{% url 'question-detail' obj.id %}">
                <strong>{{obj}}</strong>
            </a>
        </td>
        <td>
            <span>{{obj.get_question_type_display}}</span>
        </td>
        <td>
            <span>{{obj.max_answers}}</span>
        </td>
        <td>
            <button class="button is-small is-danger is-inverted " id="modal-trigger" onclick="fill_data(this)" data-target="QuestionDeleteModal" data-value="{% url 'question-delete' obj.id %}">
                <i class="fa-solid fa-trash"></i>
            </button>
        </td>
    </tr>
{% endblock table_content %}
{% block modals %}
    {% include 'partials/delete_modal.html' with modal_name="QuestionDeleteModal" object_type=_("Question") %}
{% endblock modals %}